spring:
  profiles:
      active: dev

  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/tangsir
        username: root
        password: root

mongodb:
  primary:
        host: 127.0.0.1
        port: 27017
        username: test
        password: 123
        database: tangsir

server:
  port: 8088
  context-path: /tangsir

